apigen_targets = ./api-doc/404.html \
                  ./api-doc/class-WHA_CliCmdAlreadyRegistered.html \
                  ./api-doc/class-WHA_CliCmdFactoryException.html \
                  ./api-doc/class-WHA_CliCmdFactory.html \
                  ./api-doc/class-WHA_CliCmdHelp.html \
                  ./api-doc/class-WHA_CliCmd.html \
                  ./api-doc/class-WHA_CliCmdNotRegistered.html \
                  ./api-doc/class-WHA_CliCmdSetup.html \
                  ./api-doc/class-WHA_CliCmdTest.html \
                  ./api-doc/class-WHA_CliCmdVersion.html \
                  ./api-doc/class-WHA_Cli.html \
                  ./api-doc/class-WHA_ConfEditException.html \
                  ./api-doc/class-WHA_ConfEdit.html \
                  ./api-doc/class-WHA_DialogDselect.html \
                  ./api-doc/class-WHA_DialogException.html \
                  ./api-doc/class-WHA_DialogFselect.html \
                  ./api-doc/class-WHA_DialogInputbox.html \
                  ./api-doc/class-WHA_DialogMenu.html \
                  ./api-doc/class-WHA_DialogMsgbox.html \
                  ./api-doc/class-WHA_DialogRadiolist.html \
                  ./api-doc/class-WHA_DialogWidget.html \
                  ./api-doc/class-WHA_DialogYesno.html \
                  ./api-doc/class-WHA_FileAnnotations.html \
                  ./api-doc/class-WHA_ICmd.html \
                  ./api-doc/class-WHA_Object.html \
                  ./api-doc/class-WHA_PkgQueryToolException.html \
                  ./api-doc/class-WHA_PkgQueryTool.html \
                  ./api-doc/class-WHA_ShellConfigFileAnnotations.html \
                  ./api-doc/class-WHA_ToolsException.html \
                  ./api-doc/class-WHA_Tools.html \
                  ./api-doc/elementlist.js \
                  ./api-doc/function-wha_cli_main.html \
                  ./api-doc/function-wha_command_help.html \
                  ./api-doc/function-wha_command_setup_dialog_apache_confdir.html \
                  ./api-doc/function-wha_command_setup_dialog_apache.html \
                  ./api-doc/function-wha_command_setup_dialog_apache_moddir.html \
                  ./api-doc/function-wha_command_setup_dialog_apache_pkgname.html \
                  ./api-doc/function-wha_command_setup_dialog.html \
                  ./api-doc/function-wha_command_setup_dialog_main.html \
                  ./api-doc/function-wha_command_setup_dialog_syslog_confdir.html \
                  ./api-doc/function-wha_command_setup_dialog_syslog.html \
                  ./api-doc/function-wha_command_setup_dialog_syslog_pkgname.html \
                  ./api-doc/function-wha_command_setup.html \
                  ./api-doc/function-wha_command_version.html \
                  ./api-doc/function-wha_dialog_addslashes.html \
                  ./api-doc/function-wha_dialog_calendar.html \
                  ./api-doc/function-wha_dialog_checklist.html \
                  ./api-doc/function-wha_dialog_close.html \
                  ./api-doc/function-wha_dialog_dselect.html \
                  ./api-doc/function-wha_dialog_form.html \
                  ./api-doc/function-wha_dialog_fselect.html \
                  ./api-doc/function-wha_dialog_gauge_close.html \
                  ./api-doc/function-wha_dialog_gauge_open.html \
                  ./api-doc/function-wha_dialog.html \
                  ./api-doc/function-wha_dialog_infobox.html \
                  ./api-doc/function-wha_dialog_inputbox.html \
                  ./api-doc/function-wha_dialog_inputmenu.html \
                  ./api-doc/function-wha_dialog_menu.html \
                  ./api-doc/function-wha_dialog_mixedform.html \
                  ./api-doc/function-wha_dialog_mixedgauge.html \
                  ./api-doc/function-wha_dialog_msgbox.html \
                  ./api-doc/function-wha_dialog_open.html \
                  ./api-doc/function-wha_dialog_passwordbox.html \
                  ./api-doc/function-wha_dialog_passwordform.html \
                  ./api-doc/function-wha_dialog_pause.html \
                  ./api-doc/function-wha_dialog_radiolist.html \
                  ./api-doc/function-wha_dialog_timebox.html \
                  ./api-doc/function-wha_dialog_yesno.html \
                  ./api-doc/function-wha_get_help_string.html \
                  ./api-doc/function-wha_list_clicmd_files.html \
                  ./api-doc/function-wha_locate_wha_config.html \
                  ./api-doc/function-wha_main.html \
                  ./api-doc/function-wha_parse_args_get_args_range.html \
                  ./api-doc/function-wha_parse_args.html \
                  ./api-doc/function-wha_pkg_glob_installed.html \
                  ./api-doc/function-wha_pkg_glob_re_installed.html \
                  ./api-doc/function-wha_pkg_is_installed.html \
                  ./api-doc/function-wha_pkg_list_files.html \
                  ./api-doc/function-wha_tool_close.html \
                  ./api-doc/function-wha_tool.html \
                  ./api-doc/function-wha_tool_open.html \
                  ./api-doc/function-wha_tool_run.html \
                  ./api-doc/index.html \
                  ./api-doc/package-None.html \
                  ./api-doc/package-WHA.html \
                  ./api-doc/resources/collapsed.png \
                  ./api-doc/resources/combined.js \
                  ./api-doc/resources/footer.png \
                  ./api-doc/resources/inherit.png \
                  ./api-doc/resources/resize.png \
                  ./api-doc/resources/sort.png \
                  ./api-doc/resources/style.css \
                  ./api-doc/resources/tree-cleaner.png \
                  ./api-doc/resources/tree-hasnext.png \
                  ./api-doc/resources/tree-last.png \
                  ./api-doc/resources/tree-vertical.png \
                  ./api-doc/source-class-WHA_CliCmdAlreadyRegistered.html \
                  ./api-doc/source-class-WHA_CliCmdFactoryException.html \
                  ./api-doc/source-class-WHA_CliCmdFactory.html \
                  ./api-doc/source-class-WHA_CliCmdHelp.html \
                  ./api-doc/source-class-WHA_CliCmd.html \
                  ./api-doc/source-class-WHA_CliCmdNotRegistered.html \
                  ./api-doc/source-class-WHA_CliCmdSetup.html \
                  ./api-doc/source-class-WHA_CliCmdTest.html \
                  ./api-doc/source-class-WHA_CliCmdVersion.html \
                  ./api-doc/source-class-WHA_Cli.html \
                  ./api-doc/source-class-WHA_ConfEditException.html \
                  ./api-doc/source-class-WHA_ConfEdit.html \
                  ./api-doc/source-class-WHA_DialogDselect.html \
                  ./api-doc/source-class-WHA_DialogException.html \
                  ./api-doc/source-class-WHA_DialogFselect.html \
                  ./api-doc/source-class-WHA_DialogInputbox.html \
                  ./api-doc/source-class-WHA_DialogMenu.html \
                  ./api-doc/source-class-WHA_DialogMsgbox.html \
                  ./api-doc/source-class-WHA_DialogRadiolist.html \
                  ./api-doc/source-class-WHA_DialogWidget.html \
                  ./api-doc/source-class-WHA_DialogYesno.html \
                  ./api-doc/source-class-WHA_FileAnnotations.html \
                  ./api-doc/source-class-WHA_ICmd.html \
                  ./api-doc/source-class-WHA_Object.html \
                  ./api-doc/source-class-WHA_PkgQueryToolException.html \
                  ./api-doc/source-class-WHA_PkgQueryTool.html \
                  ./api-doc/source-class-WHA_ShellConfigFileAnnotations.html \
                  ./api-doc/source-class-WHA_ToolsException.html \
                  ./api-doc/source-class-WHA_Tools.html \
                  ./api-doc/source-function-wha_cli_main.html \
                  ./api-doc/source-function-wha_command_help.html \
                  ./api-doc/source-function-wha_command_setup_dialog_apache_confdir.html \
                  ./api-doc/source-function-wha_command_setup_dialog_apache.html \
                  ./api-doc/source-function-wha_command_setup_dialog_apache_moddir.html \
                  ./api-doc/source-function-wha_command_setup_dialog_apache_pkgname.html \
                  ./api-doc/source-function-wha_command_setup_dialog.html \
                  ./api-doc/source-function-wha_command_setup_dialog_main.html \
                  ./api-doc/source-function-wha_command_setup_dialog_syslog_confdir.html \
                  ./api-doc/source-function-wha_command_setup_dialog_syslog.html \
                  ./api-doc/source-function-wha_command_setup_dialog_syslog_pkgname.html \
                  ./api-doc/source-function-wha_command_setup.html \
                  ./api-doc/source-function-wha_command_version.html \
                  ./api-doc/source-function-wha_dialog_addslashes.html \
                  ./api-doc/source-function-wha_dialog_calendar.html \
                  ./api-doc/source-function-wha_dialog_checklist.html \
                  ./api-doc/source-function-wha_dialog_close.html \
                  ./api-doc/source-function-wha_dialog_dselect.html \
                  ./api-doc/source-function-wha_dialog_form.html \
                  ./api-doc/source-function-wha_dialog_fselect.html \
                  ./api-doc/source-function-wha_dialog_gauge_close.html \
                  ./api-doc/source-function-wha_dialog_gauge_open.html \
                  ./api-doc/source-function-wha_dialog.html \
                  ./api-doc/source-function-wha_dialog_infobox.html \
                  ./api-doc/source-function-wha_dialog_inputbox.html \
                  ./api-doc/source-function-wha_dialog_inputmenu.html \
                  ./api-doc/source-function-wha_dialog_menu.html \
                  ./api-doc/source-function-wha_dialog_mixedform.html \
                  ./api-doc/source-function-wha_dialog_mixedgauge.html \
                  ./api-doc/source-function-wha_dialog_msgbox.html \
                  ./api-doc/source-function-wha_dialog_open.html \
                  ./api-doc/source-function-wha_dialog_passwordbox.html \
                  ./api-doc/source-function-wha_dialog_passwordform.html \
                  ./api-doc/source-function-wha_dialog_pause.html \
                  ./api-doc/source-function-wha_dialog_radiolist.html \
                  ./api-doc/source-function-wha_dialog_timebox.html \
                  ./api-doc/source-function-wha_dialog_yesno.html \
                  ./api-doc/source-function-wha_get_help_string.html \
                  ./api-doc/source-function-wha_list_clicmd_files.html \
                  ./api-doc/source-function-wha_locate_wha_config.html \
                  ./api-doc/source-function-wha_main.html \
                  ./api-doc/source-function-wha_parse_args_get_args_range.html \
                  ./api-doc/source-function-wha_parse_args.html \
                  ./api-doc/source-function-wha_pkg_glob_installed.html \
                  ./api-doc/source-function-wha_pkg_glob_re_installed.html \
                  ./api-doc/source-function-wha_pkg_is_installed.html \
                  ./api-doc/source-function-wha_pkg_list_files.html \
                  ./api-doc/source-function-wha_tool_close.html \
                  ./api-doc/source-function-wha_tool.html \
                  ./api-doc/source-function-wha_tool_open.html \
                  ./api-doc/source-function-wha_tool_run.html
